# Move the directory to the second line
"$schema" = 'https://starship.rs/config-schema.json'
format = """
$fill
$directory$all$character
"""
right_format = ""
add_newline = false
continuation_prompt = '> '

# A continuation prompt that displays two filled in arrows
[character]
success_symbol = "[->](bold green)"
error_symbol = "[->](bold red)"
vimcmd_symbol = "[->](bold green)"
# ~/.config/starship.toml

[aws]
symbol = "îŒ½  "
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"

[buf]
disabled=true
symbol = "ï’ "

[c]
symbol = "î˜ "
format = "\\[[$symbol($version(-$name))]($style)\\]"

[conda]
symbol = "ï„Œ "
format = "\\[[$symbol$environment]($style)\\]"

[crystal]
symbol = "î˜¯ "
format = "\\[[$symbol($version)]($style)\\]"

[dart]
symbol = "î˜ "
format = "\\[[$symbol($version)]($style)\\]"

[directory]
read_only = " ó°Œ¾"
truncation_length = 4
truncation_symbol = "..."
repo_root_style = "bold underline green"
repo_root_format = '[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

# [directory.substitutions]
# "Documents" = "D"
# "Downloads" = "ï€™ "
# "Music" = "ï€ "
# "Pictures" = "ï€¾ "
# "Videos" = "ï€½ "
# "Projects" = "ó±Œ¢ "
# "School" = "ó°‘´ "
# "www" = "îœ¥"
# ".config" = "ï£ "

[docker_context]
symbol = "ïŒˆ "
format = "\\[[$symbol$context]($style)\\]"

[elixir]
symbol = "î˜­ "
format = "\\[[$symbol($version \\(OTP $otp_version\\))]($style)\\]"

[elm]
symbol = "î˜¬ "
format = "\\[[$symbol($version)]($style)\\]"

[fennel]
symbol = "îš¯ "
format = "\\[[$symbol($version)]($style)\\]"

# [env_var.SHELL]
# variable = 'SHELL'
# style = "green"
# format = "\\[[$env_value]($style)\\]"

[fill]
symbol = "â”€"

[fossil_branch]
symbol = "ï˜ "
format = "\\[[$symbol$branch]($style)\\]"

[git_branch]
symbol = "ï˜ "
format = "\\[[$symbol$branch]($style)\\]"

[git_commit]
only_detached = false
format = "\\[[$hash$tag]($style)\\]"

[git_metrics]
disabled = false
format = "\\[[+$added]($added_style) [-$deleted]($deleted_style)\\]"

[golang]
symbol = "î˜§ "
format = "\\[[$symbol($version)]($style)\\]"

[guix_shell]
symbol = "ïŒ¥ "
format = "\\[[$symbol]($style)\\]"

[haskell]
symbol = "î· "
format = "\\[[$symbol($version)]($style)\\]"

[haxe]
symbol = "î™¦ "
format = "\\[[$symbol($version)]($style)\\]"

[hg_branch]
symbol = "ï˜ "
format = "\\[[$symbol$branch]($style)\\]"

[hostname]
ssh_symbol = "î¬ "

[java]
symbol = "î‰– "
format = "\\[[$symbol($version)]($style)\\]"

[julia]
symbol = "î˜¤ "
format = "\\[[$symbol($version)]($style)\\]"

[kotlin]
symbol = "î˜´ "
format = "\\[[$symbol($version)]($style)\\]"

[lua]
symbol = "î˜  "
format = "\\[[$symbol($version)]($style)\\]"

[memory_usage]
symbol = "ó°› "
format = "\\[$symbol[$ram( | $swap)]($style)\\]"

[meson]
symbol = "ó°”· "
format = "\\[[$symbol$project]($style)\\]"

[nim]
symbol = "ó°†¥ "
format = "\\[[$symbol($version)]($style)\\]"

[nix_shell]
symbol = "ïŒ“ "
format = "\\[[$symbol$state( \\($name\\))]($style)\\]"

[nodejs]
symbol = "îœ˜ "
format = "\\[[$symbol($version)]($style)\\]"

[ocaml]
symbol = "î™º "
format = "\\[[$symbol($version)(\\($switch_indicator$switch_name\\))]($style)\\]"

[os]
format = "\\[[$symbol]($style)\\]"

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
symbol = "ó°— "
format = "\\[[$symbol$version]($style)\\]"

[perl]
symbol = "î™¾ "
format = "\\[[$symbol($version)]($style)\\]"

[php]
symbol = "î˜ˆ "
format = "\\[[$symbol($version)]($style)\\]"

[pijul_channel]
symbol = "ï˜ "
format = "\\[[$symbol$channel]($style)\\]"

[python]
symbol = "îˆµ "
format = "\\[[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\\]"

[rlang]
symbol = "ó°Ÿ” "

[ruby]
symbol = "î‘ "
format = "\\[[$symbol($version)]($style)\\]"

[rust]
symbol = "î¨ "
format = "\\[[$symbol($version)]($style)\\]"

[scala]
symbol = "îœ· "
format = "\\[[$symbol($version)]($style)\\]"

[swift]
symbol = "î• "
format = "\\[[$symbol($version)]($style)\\]"

[zig]
symbol = "îš© "
format = "\\[[$symbol($version)]($style)\\]"

[bun]
format = "\\[[$symbol($version)]($style)\\]"

[cmake]
format = "\\[[$symbol($version)]($style)\\]"

[cmd_duration]
format = "\\[[â± $duration]($style)\\]"

[cobol]
format = "\\[[$symbol($version)]($style)\\]"

[daml]
format = "\\[[$symbol($version)]($style)\\]"

[deno]
format = "\\[[$symbol($version)]($style)\\]"

[dotnet]
format = "\\[[$symbol($version)(ğŸ¯ $tfm)]($style)\\]"

[erlang]
format = "\\[[$symbol($version)]($style)\\]"

[gcloud]
format = "\\[[$symbol$account(@$domain)(\\($region\\))]($style)\\]"

[git_status]
disabled=true
format = "([\\[$all_status$ahead_behind\\]]($style))"

[gradle]
format = "\\[[$symbol($version)]($style)\\]"

[helm]
format = "\\[[$symbol($version)]($style)\\]"

[kubernetes]
format = "\\[[$symbol$context( \\($namespace\\))]($style)\\]"

[opa]
format = "\\[[$symbol($version)]($style)\\]"

[openstack]
format = "\\[[$symbol$cloud(\\($project\\))]($style)\\]"

[pulumi]
format = "\\[[$symbol$stack]($style)\\]"

[purescript]
format = "\\[[$symbol($version)]($style)\\]"

[raku]
format = "\\[[$symbol($version-$vm_version)]($style)\\]"

[red]
format = "\\[[$symbol($version)]($style)\\]"

[spack]
format = "\\[[$symbol$environment]($style)\\]"

[sudo]
format = "\\[[as $symbol]($style)\\]"

[terraform]
format = "\\[[$symbol$workspace]($style)\\]"

[time]
format = "\\[[$time]($style)\\]"

[username]
format = "\\[[$user]($style)\\]"


[vagrant]
format = "\\[[$symbol($version)]($style)\\]"

[vlang]
format = "\\[[$symbol($version)]($style)\\]"

[solidity]
format = "\\[[$symbol($version)]($style)\\]"


